beer_index:
    path:     /
    defaults: { _controller: "BeerScoreBundle:Beer:index" }
    methods:  GET

beer_show:
    path:     /{id}/show
    defaults: { _controller: "BeerScoreBundle:Beer:show" }
    methods:  GET

beer_new:
    path:     /new
    defaults: { _controller: "BeerScoreBundle:Beer:new" }
    methods:  [GET, POST]

beer_edit:
    path:     /{id}/edit
    defaults: { _controller: "BeerScoreBundle:Beer:edit" }
    methods:  [GET, POST]

beer_delete:
    path:     /{id}/delete
    defaults: { _controller: "BeerScoreBundle:Beer:delete" }
    methods:  DELETE

beer_add_review:
    path:     /{id}/addReview
    defaults: { _controller: "BeerScoreBundle:Beer:addReview" }
    methods:  [GET, POST]
